# Simple Reinforcement Learning with Tensorflow: Part 0 - Q-Tables
In this iPython notebook we implement a Q-Table algorithm that solves the FrozenLake problem. To learn more, read here: https://medium.com/@awjuliani/simple-reinforcement-learning-with-tensorflow-part-0-q-learning-with-tables-and-neural-networks-d195264329d0

For more reinforcment learning tutorials, see:
https://github.com/awjuliani/DeepRL-Agents

In [41]:
import gym
import numpy as np
import random
import matplotlib.pyplot as plt
%matplotlib inline

### Load the environment

In [42]:
env = gym.make('FrozenLake-v0')

### Implement Q-Table learning algorithm

In [43]:
#Initialize table with all zeros
Q = np.zeros([env.observation_space.n,env.action_space.n])
# Set learning parameters
lr = .8
y = .95
num_episodes = 2000
#create lists to contain total rewards and steps per episode
#jList = []
rList = []
for i in range(num_episodes):
    #Reset environment and get first new observation
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    #The Q-Table learning algorithm
    while j < 99:
        j+=1
        #Choose an action by greedily (with noise) picking from Q table
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
        if i == 1998 and j == 1:
            print(s,a,s1,r,d,i,j,Q[s,:],np.random.randn(1,env.action_space.n)*(1./(i+1)))
            print(Q)
        #Get new state and reward from environment
        s1,r,d,info = env.step(a)
        #Update Q-Table with new knowledge
        Q[s,a] = Q[s,a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        if i == 1998 and j<16:
            print(s,a,s1,r,d,i,j,Q[s,:],np.random.randn(1,env.action_space.n)/(i+1.))
            print(Q)
        s = s1
        if d == True:
            break
    #jList.append(j)
    rList.append(rAll)

0 2 15 1.0 False 1998 1 [0.00195527 0.00381744 0.15895618 0.00201819] [[ 9.15207656e-04 -3.25213857e-04 -1.83332792e-04  7.56383494e-05]]
[[1.95527286e-03 3.81744137e-03 1.58956179e-01 2.01819318e-03]
 [1.50848523e-05 9.27504560e-05 6.99716367e-04 5.73179040e-02]
 [5.64143301e-04 8.29941171e-04 5.69675392e-04 2.52392483e-02]
 [1.74350564e-04 4.33134405e-04 4.28859825e-04 2.20145223e-02]
 [2.90801045e-01 2.83925132e-04 1.10706810e-03 4.36406481e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.07712928e-04 3.20066760e-09 2.49862421e-02 5.97513986e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [2.99139770e-04 0.00000000e+00 0.00000000e+00 4.01227861e-01]
 [0.00000000e+00 6.02265450e-01 0.00000000e+00 0.00000000e+00]
 [3.78572165e-01 5.06921853e-04 6.04835343e-04 5.78406515e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 8.94385174e

In [44]:
print("Score over time: " +  str(sum(rList)/num_episodes))

Score over time: 0.404


In [45]:
print("Final Q-Table Values")
print(Q)

Final Q-Table Values
[[1.95527286e-03 3.81744137e-03 2.64039042e-01 2.01819318e-03]
 [1.50848523e-05 9.27504560e-05 6.99716367e-04 4.29051012e-02]
 [5.64143301e-04 8.29941171e-04 5.69675392e-04 2.47222846e-02]
 [1.74350564e-04 4.33134405e-04 4.28859825e-04 1.53268592e-02]
 [2.97704159e-01 2.83925132e-04 1.10706810e-03 4.36406481e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.07712928e-04 3.20066760e-09 2.49862421e-02 5.97513986e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [2.99139770e-04 0.00000000e+00 0.00000000e+00 5.16748818e-01]
 [0.00000000e+00 7.61366319e-01 0.00000000e+00 0.00000000e+00]
 [3.85922064e-01 5.06921853e-04 6.04835343e-04 5.78406515e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 8.50931685e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 9.62990938e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.